In [12]:
import numpy as np
import pandas as pd
from sklearn import tree

In [13]:
DSCustomerChurn = pd.read_csv('/content/Mall_Customers.csv', delimiter=',', header=0)

#mengubah kelas dari string ke unique-integer
DSCustomerChurn["Genre"] = pd.factorize(DSCustomerChurn.Genre)[0]

#jika ingin drop kolom
#DSCustomerChurn = DSCustomerChurn.drop(labels="Gender", axis=1)
#ubah dataframe ke array numpy matrix
DSCustomerChurn = DSCustomerChurn.to_numpy()

In [14]:
print(DSCustomerChurn)

[[  1   0  19  15  39]
 [  2   0  21  15  81]
 [  3   1  20  16   6]
 [  4   1  23  16  77]
 [  5   1  31  17  40]
 [  6   1  22  17  76]
 [  7   1  35  18   6]
 [  8   1  23  18  94]
 [  9   0  64  19   3]
 [ 10   1  30  19  72]
 [ 11   0  67  19  14]
 [ 12   1  35  19  99]
 [ 13   1  58  20  15]
 [ 14   1  24  20  77]
 [ 15   0  37  20  13]
 [ 16   0  22  20  79]
 [ 17   1  35  21  35]
 [ 18   0  20  21  66]
 [ 19   0  52  23  29]
 [ 20   1  35  23  98]
 [ 21   0  35  24  35]
 [ 22   0  25  24  73]
 [ 23   1  46  25   5]
 [ 24   0  31  25  73]
 [ 25   1  54  28  14]
 [ 26   0  29  28  82]
 [ 27   1  45  28  32]
 [ 28   0  35  28  61]
 [ 29   1  40  29  31]
 [ 30   1  23  29  87]
 [ 31   0  60  30   4]
 [ 32   1  21  30  73]
 [ 33   0  53  33   4]
 [ 34   0  18  33  92]
 [ 35   1  49  33  14]
 [ 36   1  21  33  81]
 [ 37   1  42  34  17]
 [ 38   1  30  34  73]
 [ 39   1  36  37  26]
 [ 40   1  20  37  75]
 [ 41   1  65  38  35]
 [ 42   0  24  38  92]
 [ 43   0  48  39  36]
 [ 44   1  

In [17]:
dataTraining = np.concatenate((DSCustomerChurn[0:40, :], DSCustomerChurn[50:90, :]), axis=0)
dataTesting = np.concatenate((DSCustomerChurn[40:50, :], DSCustomerChurn[90:100, :]), axis=0)
inputTraining = dataTraining[:, 0:5]
inputTesting = dataTesting[:, 0:5]
labelTraining = dataTraining[:, 4]
labelTesting = dataTesting[:, 4]

In [18]:
model = tree.DecisionTreeClassifier()
#training model
model = model.fit(inputTraining, labelTraining)
#prediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("label sebenarnya", labelTesting)
print("hasil prediksi", hasilPrediksi)
#hitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("prediksi benar: ", prediksiBenar, "data")
print("prediksi salah: ", prediksiSalah, "data")
print("akurasi: ", prediksiBenar/(prediksiBenar+prediksiSalah)*100, "%")

label sebenarnya [35 92 36 61 28 65 55 47 42 42 55 41 49 40 42 52 47 50 42 49]
hasil prediksi [45 87 29 61 45 61 55 50 40 40 55 41 49 42 42 52 47 49 41 49]
prediksi benar:  9 data
prediksi salah:  11 data
akurasi:  45.0 %
